set shell := ["bash", "-euo", "pipefail", "-c"]

alias c := check

fmt:
  npm run fmt

fmt-check:
  npm run fmt:check

typecheck:
  npm run typecheck

lint:
  npm run lint

test:
  npm run test

check: typecheck fmt-check lint test
